from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardRemove
ikb = InlineKeyboardMarkup()
button1 = InlineKeyboardButton(text="🚀 Регистрация", callback_data="registr")
button2 = InlineKeyboardButton(text="📚 Инструкция", callback_data="instr")
ikb.add(button1)
ikb.add(button2)

ikb2 = InlineKeyboardMarkup()
button3 = InlineKeyboardButton(text="🎮 Меню", callback_data="menu")
ikb2.add(button3)
ikb3 = InlineKeyboardMarkup()
button4 = InlineKeyboardButton(text="Попробовать ещё раз 🛑", callback_data="not_login")
ikb3.add(button4)
ikb4 = InlineKeyboardMarkup()
button5 = InlineKeyboardButton(text="Получить сигнал 🎯", callback_data="signal")
ikb4.add(button5)
ikb5 = InlineKeyboardMarkup()
button6 = InlineKeyboardButton(text="Следущий сигнал 💥", callback_data="signal")
ikb5.add(button6)